import type { CreativeFinishedArticleMode } from "./types.js";

// 写作流程单步追踪记录
export type StepTraceEntry = {
  step: number;
  stepName: string;
  status: string;
  startedAt?: string;
  finishedAt?: string;
  durationMs?: number;
  summary?: string;
  error?: string;
  meta?: Record<string, unknown>;
};

export type ArticleRewriteLevel = "light" | "medium" | "heavy";

export type TitleCandidate = {
  title: string;
  group: "impact" | "risk" | "counterintuitive" | "action";
  group_label: string;
  target_reader: string;
  click_reason: string;
  content_payoff: string;
  clickbait_risk: "low" | "medium" | "high";
  recommendation: "high" | "medium" | "low" | "fallback";
  reader_task?: string;
};

export type CreativeFinishedArticleRecord = {
  id: number;
  sourceItemId: number | null;
  mode: CreativeFinishedArticleMode | null;
  thesis: string | null;
  intros: string[] | null;
  contentMarkdown: string;
  humanMarkdown: string | null;
  titles: string[] | null;
  hooks: string[] | null;
  quotes: string[] | null;
  summary100: string[] | null;
  imagesJson: unknown[] | null;
  images: unknown[] | null;
  coverImage: string[];
  coverImageIndex: number;
  titleIndex: number;
  introIndex: number;
  summaryIndex: number;
  status: string;
  anomalyReason: string | null;
  rawResponseText: string | null;
  wechatPublished: boolean;
  publishable: boolean;
  coverImagePrompt: string | null;
  inlineImagePrompts: Record<string, string> | null;
  similarityCheck: Record<string, unknown> | null;
  needsManualReview: boolean;
  manualReviewReason: string | null;
  manualReviewReasons: string[] | null;
  stepTrace: StepTraceEntry[] | null;
  currentStep: number | null;
  stopStep: number | null;
  reasonCode: string | null;
  reasonText: string | null;
  deletedAt: string | null;
  wechatThemeId: string | null;
  wechatHtml: string | null;
  direction: string;
  seqNumber: number | null;
  form: string | null;
  reversalScore: number | null;
  reversalAngle: string | null;
  imagePrompts: string[] | null;
  comments: { reader: string; author_reply: string }[] | null;
  authorExtensions: string[] | null;
  pipelineVersion: string | null;
  readerTask: string | null;
  readerRelevance: Record<string, unknown> | null;
  evidencePack: Record<string, unknown> | null;
  readerValuePlan: Record<string, unknown> | null;
  factSkeleton: Record<string, unknown> | null;
  oralDraft: string | null;
  titleCandidates: TitleCandidate[] | null;
  factSourceChecklist: unknown[] | null;
  titleSelectionConfirmed: boolean;
  performanceDeliveredUsers: number | null;
  performanceReadUsers: number | null;
  performanceShareUsers: number | null;
  performanceNewFollowers: number | null;
  performanceRewriteLevel: ArticleRewriteLevel | null;
  performanceTitleSnapshot: string | null;
  performanceTitleGroupSnapshot: string | null;
  performanceReaderTaskSnapshot: string | null;
  performanceRecordedAt: string | null;
  originType: "pipeline" | "manual";
  pinnedAt: string | null;
  pushCount: number;
  createdAt: string;
  updatedAt: string;
};

export type InsertCreativeFinishedArticleInput = {
  sourceItemId?: number | null;
  mode?: CreativeFinishedArticleMode;
  thesis?: string;
  intros?: string[];
  contentMarkdown: string;
  humanMarkdown?: string | null;
  titles?: string[];
  hooks?: string[];
  quotes?: string[];
  summary100?: string[];
  images?: unknown[];
  coverImage?: string[];
  rawResponseText?: string;
  coverImagePrompt?: string;
  inlineImagePrompts?: Record<string, string>;
  similarityCheck?: Record<string, unknown>;
  needsManualReview?: boolean;
  manualReviewReason?: string;
  manualReviewReasons?: string[];
  status?: string;
  anomalyReason?: string;
  stepTrace?: StepTraceEntry[];
  currentStep?: number;
  stopStep?: number;
  reasonCode?: string;
  reasonText?: string;
  direction?: string;
  form?: string;
  reversalScore?: number;
  reversalAngle?: string;
  imagePrompts?: string[];
  comments?: { reader: string; author_reply: string }[];
  authorExtensions?: string[];
  pipelineVersion?: string;
  readerTask?: string;
  readerRelevance?: Record<string, unknown>;
  evidencePack?: Record<string, unknown>;
  readerValuePlan?: Record<string, unknown>;
  factSkeleton?: Record<string, unknown>;
  oralDraft?: string;
  titleCandidates?: TitleCandidate[];
  factSourceChecklist?: unknown[];
  titleSelectionConfirmed?: boolean;
  titleIndex?: number;
  originType?: "pipeline" | "manual";
};

export type EditCreativeFinishedArticleInput = {
  mode?: CreativeFinishedArticleMode;
  thesis?: string;
  intros?: string[];
  introIndex?: number;
  contentMarkdown?: string;
  humanMarkdown?: string | null;
  titles?: string[];
  hooks?: string[];
  quotes?: string[];
  summary100?: string[];
  summaryIndex?: number;
  images?: unknown[];
  coverImage?: string[];
  coverImageIndex?: number;
  titleIndex?: number;
  rawResponseText?: string;
  status?: string;
  anomalyReason?: string | null;
  wechatThemeId?: string | null;
  wechatHtml?: string | null;
  coverImagePrompt?: string;
  inlineImagePrompts?: Record<string, string>;
  imagePrompts?: string[];
  comments?: { reader: string; author_reply: string }[];
  authorExtensions?: string[];
  similarityCheck?: Record<string, unknown>;
  needsManualReview?: boolean;
  manualReviewReason?: string;
  manualReviewReasons?: string[];
  stepTrace?: StepTraceEntry[];
  currentStep?: number;
  stopStep?: number;
  reasonCode?: string;
  reasonText?: string;
  titleCandidates?: TitleCandidate[];
  titleSelectionConfirmed?: boolean;
};

export type ListCreativeFinishedArticlesFilters = {
  page?: number;
  pageSize?: number;
  status?: string;
  search?: string;
  publishable?: boolean;
  includeDeleted?: boolean;
  direction?: string;
  summaryOnly?: boolean;
};

export type ListCreativeFinishedArticlesResult = {
  items: CreativeFinishedArticleRecord[];
  total: number;
  page: number;
  pageSize: number;
};

export type SaveArticlePerformanceFeedbackInput = {
  deliveredUsers: number;
  readUsers: number;
  shareUsers: number;
  newFollowers?: number | null;
  rewriteLevel: ArticleRewriteLevel;
};
